apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-containers
        image: nginx:latest
        ports:
        - containerPort: 80


