apiVersion: v1
kind: Service
metadata:
  name: dservice
  labels:
    app: demo-app
spec: 
  selector:
    app: demo-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
