# argoworkflow/apps/base/orders/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-backend
  labels:
    app: orders
spec:
  replicas: 1 # You can adjust this based on your needs
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: your-repo/orders-backend:latest # Replace with your actual image
          ports:
            - containerPort: 8080 # The port your orders app listens on
          env:
            # Example environment variables, replace with your actual ones
            - name: DATABASE_HOST
              value: "orders-db-service"
            - name: DATABASE_PORT
              value: "5432"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: api-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
